##### Stage 1
FROM node:latest as node
LABEL author="Sunil K"
WORKDIR /app
COPY package.json package.json
RUN npm install --force
COPY . .
RUN npm run build

##### Stage 2
FROM nginx:alpine
ADD docker/harden.sh / 
RUN chmod 700 /harden.sh \
	&& sh -c "/harden.sh" \
	&& rm -rf /harden.sh
VOLUME /var/cache/nginx
COPY --from=node /app/dist /usr/share/nginx/html
COPY ./config/nginx/default.conf /etc/nginx/conf.d/default.conf

#docker build -t weather .
#docker run -p 80:80 weather
