management:
  endpoint:
    info:
      enabled: true
    restart:
      enabled: true
    health:
      probes:
        enabled: true
server:
  port: 8083
  ssl:
    key-alias: server
    key-store: /app/springboot.jks
    key-store-type: JKS
    key-password: changeit
spring:
  main:
    allow-circular-references: true
  application:
    name: nextwork-admin-service
  data:
    mongodb:
#      uri: mongodb://admin:nextwork@localhost:27017/nextworkdb?authSource=admin
      uri: mongodb://localhost:27017/nextworkdb
#      host: ${SPRING_DATA_MONGODB_HOST}
#      port: ${SPRING_DATA_MONGODB_PORT}
#      username: ${SPRING_DATA_MONGODB_USERNAME}
#      password: ${SPRING_DATA_MONGODB_PASSWORD}
##      database: ${SPRING_DATA_MONGODB_DATABASE}
#      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri:  ${SECURITY_OAUTH2_RESOURCESERVER_JWT_JWT_SET_URI}

remote-service-base:
  url: http://localhost:8081
project-service:
  url: /api/v1/project
user-service:
  url: /api/v1/user
s3bucket:
  app-bucket-name: ${S3_BUCKET}

---
spring:
  profiles: prod
remote-service-base:
  url: ${REMOTE_SERVICE_BASE_URL}

