package com.siemens.nextwork.admin.enums;

public enum AllTierEnum {
    WIN("Win"),
    GROW("Grow"),
    BOND("Bond"),
    RESHUFFLE("Reshuffle"),
    MAINTAIN("Maintain"),
    WIN_GROW("Win Grow"),
    WIN_BOND("Win Bond"),
    GROW_BOND("Grow Bond"),
    WIN_GROW_BOND("Win Grow Bond"),
    WIN_2GROWTH_HIRE("Growth Hire"),
    WIN_2REPLACEMENT_HIRE("Replacement Hire"),
    GROW_2UPSKILL("Upskill"),
    GROW_2RESKILL("Reskill"),
    BOND_2ATTRACTIVE_CONDITION("Attractive Condition"),
    BOND_2STRONG_CULTURE("Strong Culture"),
    BOND_2FULL_POTENTIAL("Full Potential"),
    RESHUFFLE_2INVOLUNTARY_EXITS("Involuntary Exits"),
    RESHUFFLE_2VOLUNTARY_EXITS("Voluntary Exits"),
    WIN_2GROWTH_HIRE_3TAKE_OVER("Take Over"),
    WIN_2GROWTH_HIRE_3INTERNAL_HIRE("Internal Hire"),
    WIN_2GROWTH_HIRE_3EXTERNAL_HIRE("External Hire"),
    WIN_2GROWTH_HIRE_3TEMPORARY_CONTACT("Temporary Contact"),
    WIN_2REPLACEMENT_HIRE_3TAKE_OVER("Take Over"),
    WIN_2REPLACEMENT_HIRE_3INTERNAL_HIRE("Internal Hire"),
    WIN_2REPLACEMENT_HIRE_3EXTERNAL_HIRE("External Hire"),
    WIN_2REPLACEMENT_HIRE_3TEMPORARY_CONTACT("Temporary Contact"),
    GROW_2UPSKILL_3MY_LEARNING_WORLD("My Learning World"),
    GROW_2UPSKILL_3SITECSKILLS("Sitecskills"),
    GROW_2UPSKILL_3SABA("Saba"),
    GROW_2UPSKILL_3QUALIFICATION("Qualification"),
    GROW_2RESKILL_3MY_LEARNING_WORLD("My Learning World"),
    GROW_2RESKILL_3SITECSKILLS("Sitecskills"),
    GROW_2RESKILL_3SABA("Saba"),
    GROW_2RESKILL_3QUALIFICATION("Qualification"),
    BOND_2ATTRACTIVE_CONDITION_3COMPENSATION("Compensation"),
    BOND_2ATTRACTIVE_CONDITION_3BENEFITS("Benefits"),
    BOND_2ATTRACTIVE_CONDITION_3RECOGNISTION("Recognistion"),
    BOND_2ATTRACTIVE_CONDITION_3FLEX_AND_SELF_DETERMINATION("Flex And Self Determination"),
    BOND_2ATTRACTIVE_CONDITION_3WELL_BEING("Well Being"),
    BOND_2ATTRACTIVE_CONDITION_3PEOPLE_EXPERIENCE("People Experience"),
    BOND_2STRONG_CULTURE_3PURPOSE("Purpose"),
    BOND_2STRONG_CULTURE_3LEADERSHIP("Leadership"),
    RESHUFFLE_2INVOLUNTARY_EXITS_3EARLY_RETIREMENT("Early Retirement"),
    RESHUFFLE_2INVOLUNTARY_EXITS_3WITH_OUTPLACEMENT("With Outplacement"),
    RESHUFFLE_2INVOLUNTARY_EXITS_3WITHOUT_OUTPLACEMENT("Without Outplacement"),
    RESHUFFLE_2VOLUNTARY_EXITS_3EARLY_RETIREMENT("Early Retirement"),
    RESHUFFLE_2VOLUNTARY_EXITS_3WITH_OUTPLACEMENT("With Outplacement"),
    RESHUFFLE_2VOLUNTARY_EXITS_3WITHOUT_OUTPLACEMENT("Without Outplacement");
	
	
    public final String value;
    private AllTierEnum(String value) {
       this.value = value;
    }

}
